// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : $Revision:   1.151.1.0.1.27  $
// File generated on 2002/6/3 ¤W¤È 12:37:03 from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\Paul\CBuilder6\Example\Charp11\Project11_7.tlb (1)
// LIBID: {D1FF36E2-23B2-45EE-84A3-C5BE5F1B9424}
// LCID: 0
// Helpfile: 
// HelpString: Project11_7 Library
// DepndLst: 
//   (1) v2.0 stdole, (C:\WINNT\System32\stdole2.tlb)
//   (2) v1.0 Midas, (C:\WINNT\System32\midas.dll)
//   (3) v4.0 StdVCL, (C:\WINNT\System32\STDVCL40.DLL)
// ************************************************************************ //
#ifndef   Project11_7_TLBH
#define   Project11_7_TLBH

#pragma option push -b -w-inl

#include <utilcls.h>
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0600)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if defined(USING_ATLVCL) || defined(USING_ATL)
#if !defined(__TLB_NO_EVENT_WRAPPERS)
#include <atl/atlmod.h>
#endif
#endif

#include "databkr.hpp"

using Midas::IAppServer;

// *********************************************************************//
// Forward reference of some VCL types (to avoid including STDVCL.HPP)    
// *********************************************************************//
namespace Stdvcl {class IStrings; class IStringsDisp;}
using namespace Stdvcl;
typedef TComInterface<IStrings> IStringsPtr;
typedef TComInterface<IStringsDisp> IStringsDispPtr;

namespace Project11_7_tlb
{

// *********************************************************************//
// HelpString: Project11_7 Library
// Version:    1.0
// *********************************************************************//


// *********************************************************************//
// GUIDS declared in the TypeLibrary. Following prefixes are used:        
//   Type Libraries     : LIBID_xxxx                                      
//   CoClasses          : CLSID_xxxx                                      
//   DISPInterfaces     : DIID_xxxx                                       
//   Non-DISP interfaces: IID_xxxx                                        
// *********************************************************************//
extern "C" const __declspec(selectany) GUID LIBID_Project11_7 = {0xD1FF36E2, 0x23B2, 0x45EE,{ 0x84, 0xA3, 0xC5,0xBE, 0x5F, 0x1B,0x94, 0x24} };
extern "C" const __declspec(selectany) GUID IID_ITest117Server = {0x381E8D28, 0xA59E, 0x4E49,{ 0xB7, 0xFE, 0x93,0x5D, 0x3D, 0x23,0xCE, 0x02} };
extern "C" const __declspec(selectany) GUID CLSID_Test117Server = {0x292F37B8, 0xD8CE, 0x4970,{ 0xAB, 0xB6, 0x29,0x52, 0xB0, 0x1A,0x92, 0x73} };

// *********************************************************************//
// Forward declaration of types defined in TypeLibrary                    
// *********************************************************************//
interface DECLSPEC_UUID("{381E8D28-A59E-4E49-B7FE-935D3D23CE02}") ITest117Server;
typedef TComInterface<ITest117Server, &IID_ITest117Server> ITest117ServerPtr;


// *********************************************************************//
// Declaration of CoClasses defined in Type Library                       
// (NOTE: Here we map each CoClass to its Default Interface)              
//                                                                        
// The LIBID_OF_ macro(s) map a LIBID_OF_CoClassName to the GUID of this  
// TypeLibrary. It simplifies the updating of macros when CoClass name    
// change.                                                                
// *********************************************************************//

#define LIBID_OF_Test117Server (&LIBID_Project11_7)
// *********************************************************************//
// Interface: ITest117Server
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {381E8D28-A59E-4E49-B7FE-935D3D23CE02}
// *********************************************************************//
interface ITest117Server  : public IAppServer
{
public:

#if !defined(__TLB_NO_INTERFACE_WRAPPERS)



#endif //   __TLB_NO_INTERFACE_WRAPPERS

};

#if !defined(__TLB_NO_INTERFACE_WRAPPERS)
// *********************************************************************//
// SmartIntf: TCOMITest117Server
// Interface: ITest117Server
// *********************************************************************//
template <class T /* ITest117Server */ >
class TCOMITest117ServerT : public TComInterface<ITest117Server>, public TComInterfaceBase<IUnknown>
{
public:
  TCOMITest117ServerT() {}
  TCOMITest117ServerT(ITest117Server *intf, bool addRef = false) : TComInterface<ITest117Server>(intf, addRef) {}
  TCOMITest117ServerT(const TCOMITest117ServerT& src) : TComInterface<ITest117Server>(src) {}
  TCOMITest117ServerT& operator=(const TCOMITest117ServerT& src) { Bind(src, true); return *this;}


};
typedef TCOMITest117ServerT<ITest117Server> TCOMITest117Server;

// *********************************************************************//
// DispIntf:  ITest117Server
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {381E8D28-A59E-4E49-B7FE-935D3D23CE02}
// *********************************************************************//
template<class T>
class ITest117ServerDispT : public TAutoDriver<ITest117Server>
{
public:
  ITest117ServerDispT(){}

  ITest117ServerDispT(ITest117Server *pintf)
  {
    TAutoDriver<ITest117Server>::Bind(pintf, false);
  }

  ITest117ServerDispT(ITest117ServerPtr pintf)
  {
    TAutoDriver<ITest117Server>::Bind(pintf, true);
  }

  ITest117ServerDispT& operator=(ITest117Server *pintf)
  {
    TAutoDriver<ITest117Server>::Bind(pintf, false);
    return *this;
  }

  ITest117ServerDispT& operator=(ITest117ServerPtr pintf)
  {
    TAutoDriver<ITest117Server>::Bind(pintf, true);
    return *this;
  }

  HRESULT BindDefault()
  {
    return OLECHECK(Bind(CLSID_Test117Server));
  }

  HRESULT BindRunning()
  {
    return BindToActive(CLSID_Test117Server);
  }

  HRESULT         __fastcall AS_ApplyUpdates(BSTR ProviderName/*[in]*/, VARIANT Delta/*[in]*/, 
                                             long MaxErrors/*[in]*/, long* ErrorCount/*[out]*/, 
                                             VARIANT* OwnerData/*[in,out]*/, 
                                             VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall AS_ApplyUpdates(BSTR ProviderName/*[in]*/, VARIANT Delta/*[in]*/, 
                                             long MaxErrors/*[in]*/, long* ErrorCount/*[out]*/, 
                                             VARIANT* OwnerData/*[in,out]*/);
  HRESULT         __fastcall AS_GetRecords(BSTR ProviderName/*[in]*/, long Count/*[in]*/, 
                                           long* RecsOut/*[out]*/, long Options/*[in]*/, 
                                           BSTR CommandText/*[in]*/, VARIANT* Params/*[in,out]*/, 
                                           VARIANT* OwnerData/*[in,out]*/, 
                                           VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall AS_GetRecords(BSTR ProviderName/*[in]*/, long Count/*[in]*/, 
                                           long* RecsOut/*[out]*/, long Options/*[in]*/, 
                                           BSTR CommandText/*[in]*/, VARIANT* Params/*[in,out]*/, 
                                           VARIANT* OwnerData/*[in,out]*/);
  HRESULT         __fastcall AS_DataRequest(BSTR ProviderName/*[in]*/, VARIANT Data/*[in]*/, 
                                            VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall AS_DataRequest(BSTR ProviderName/*[in]*/, VARIANT Data/*[in]*/);
  HRESULT         __fastcall AS_GetProviderNames(VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall AS_GetProviderNames(void);
  HRESULT         __fastcall AS_GetParams(BSTR ProviderName/*[in]*/, VARIANT* OwnerData/*[in,out]*/
                                          , VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall AS_GetParams(BSTR ProviderName/*[in]*/, VARIANT* OwnerData/*[in,out]*/);
  HRESULT         __fastcall AS_RowRequest(BSTR ProviderName/*[in]*/, VARIANT Row/*[in]*/, 
                                           long RequestType/*[in]*/, VARIANT* OwnerData/*[in,out]*/
                                           , VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall AS_RowRequest(BSTR ProviderName/*[in]*/, VARIANT Row/*[in]*/, 
                                           long RequestType/*[in]*/, VARIANT* OwnerData/*[in,out]*/);
  HRESULT         __fastcall AS_Execute(BSTR ProviderName/*[in]*/, BSTR CommandText/*[in]*/, 
                                        VARIANT* Params/*[in,out]*/, VARIANT* OwnerData/*[in,out]*/);


};
typedef ITest117ServerDispT<ITest117Server> ITest117ServerDisp;

// *********************************************************************//
// SmartIntf: TCOMITest117Server
// Interface: ITest117Server
// *********************************************************************//
// *********************************************************************//
// DispIntf:  ITest117Server
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {381E8D28-A59E-4E49-B7FE-935D3D23CE02}
// *********************************************************************//
template <class T> HRESULT __fastcall
ITest117ServerDispT<T>::AS_ApplyUpdates(BSTR ProviderName/*[in]*/, VARIANT Delta/*[in]*/, 
                                        long MaxErrors/*[in]*/, long* ErrorCount/*[out]*/, 
                                        VARIANT* OwnerData/*[in,out]*/, 
                                        VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_ApplyUpdates"), DISPID(20000000));
  TAutoArgs<5> _args;
  _args[1] = ProviderName /*[VT_BSTR:0]*/;
  _args[2] = Delta /*[VT_VARIANT:0]*/;
  _args[3] = MaxErrors /*[VT_I4:0]*/;
  _args[4] = ErrorCount /*[VT_I4:1]*/;
  _args[5] = OwnerData /*[VT_VARIANT:1]*/;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
ITest117ServerDispT<T>::AS_ApplyUpdates(BSTR ProviderName/*[in]*/, VARIANT Delta/*[in]*/, 
                                        long MaxErrors/*[in]*/, long* ErrorCount/*[out]*/, 
                                        VARIANT* OwnerData/*[in,out]*/)
{
  VARIANT Value;
  this->AS_ApplyUpdates(ProviderName, Delta, MaxErrors, ErrorCount, OwnerData, (VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITest117ServerDispT<T>::AS_GetRecords(BSTR ProviderName/*[in]*/, long Count/*[in]*/, 
                                      long* RecsOut/*[out]*/, long Options/*[in]*/, 
                                      BSTR CommandText/*[in]*/, VARIANT* Params/*[in,out]*/, 
                                      VARIANT* OwnerData/*[in,out]*/, VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_GetRecords"), DISPID(20000001));
  TAutoArgs<7> _args;
  _args[1] = ProviderName /*[VT_BSTR:0]*/;
  _args[2] = Count /*[VT_I4:0]*/;
  _args[3] = RecsOut /*[VT_I4:1]*/;
  _args[4] = Options /*[VT_I4:0]*/;
  _args[5] = CommandText /*[VT_BSTR:0]*/;
  _args[6] = Params /*[VT_VARIANT:1]*/;
  _args[7] = OwnerData /*[VT_VARIANT:1]*/;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
ITest117ServerDispT<T>::AS_GetRecords(BSTR ProviderName/*[in]*/, long Count/*[in]*/, 
                                      long* RecsOut/*[out]*/, long Options/*[in]*/, 
                                      BSTR CommandText/*[in]*/, VARIANT* Params/*[in,out]*/, 
                                      VARIANT* OwnerData/*[in,out]*/)
{
  VARIANT Value;
  this->AS_GetRecords(ProviderName, Count, RecsOut, Options, CommandText, Params, OwnerData, (VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITest117ServerDispT<T>::AS_DataRequest(BSTR ProviderName/*[in]*/, VARIANT Data/*[in]*/, 
                                       VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_DataRequest"), DISPID(20000002));
  TAutoArgs<2> _args;
  _args[1] = ProviderName /*[VT_BSTR:0]*/;
  _args[2] = Data /*[VT_VARIANT:0]*/;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
ITest117ServerDispT<T>::AS_DataRequest(BSTR ProviderName/*[in]*/, VARIANT Data/*[in]*/)
{
  VARIANT Value;
  this->AS_DataRequest(ProviderName, Data, (VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITest117ServerDispT<T>::AS_GetProviderNames(VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_GetProviderNames"), DISPID(20000003));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
ITest117ServerDispT<T>::AS_GetProviderNames(void)
{
  VARIANT Value;
  this->AS_GetProviderNames((VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITest117ServerDispT<T>::AS_GetParams(BSTR ProviderName/*[in]*/, VARIANT* OwnerData/*[in,out]*/, 
                                     VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_GetParams"), DISPID(20000004));
  TAutoArgs<2> _args;
  _args[1] = ProviderName /*[VT_BSTR:0]*/;
  _args[2] = OwnerData /*[VT_VARIANT:1]*/;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
ITest117ServerDispT<T>::AS_GetParams(BSTR ProviderName/*[in]*/, VARIANT* OwnerData/*[in,out]*/)
{
  VARIANT Value;
  this->AS_GetParams(ProviderName, OwnerData, (VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITest117ServerDispT<T>::AS_RowRequest(BSTR ProviderName/*[in]*/, VARIANT Row/*[in]*/, 
                                      long RequestType/*[in]*/, VARIANT* OwnerData/*[in,out]*/, 
                                      VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_RowRequest"), DISPID(20000005));
  TAutoArgs<4> _args;
  _args[1] = ProviderName /*[VT_BSTR:0]*/;
  _args[2] = Row /*[VT_VARIANT:0]*/;
  _args[3] = RequestType /*[VT_I4:0]*/;
  _args[4] = OwnerData /*[VT_VARIANT:1]*/;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
ITest117ServerDispT<T>::AS_RowRequest(BSTR ProviderName/*[in]*/, VARIANT Row/*[in]*/, 
                                      long RequestType/*[in]*/, VARIANT* OwnerData/*[in,out]*/)
{
  VARIANT Value;
  this->AS_RowRequest(ProviderName, Row, RequestType, OwnerData, (VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITest117ServerDispT<T>::AS_Execute(BSTR ProviderName/*[in]*/, BSTR CommandText/*[in]*/, 
                                   VARIANT* Params/*[in,out]*/, VARIANT* OwnerData/*[in,out]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_Execute"), DISPID(20000006));
  TAutoArgs<4> _args;
  _args[1] = ProviderName /*[VT_BSTR:0]*/;
  _args[2] = CommandText /*[VT_BSTR:0]*/;
  _args[3] = Params /*[VT_VARIANT:1]*/;
  _args[4] = OwnerData /*[VT_VARIANT:1]*/;
  return OleFunction(_dispid, _args);
}

// *********************************************************************//
// The following typedefs expose classes (named CoCoClassName) that       
// provide static Create() and CreateRemote(LPWSTR machineName) methods   
// for creating an instance of an exposed object. These functions can     
// be used by client wishing to automate CoClasses exposed by this        
// typelibrary.                                                           
// *********************************************************************//

// *********************************************************************//
// COCLASS DEFAULT INTERFACE CREATOR
// CoClass  : Test117Server
// Interface: TCOMITest117Server
// *********************************************************************//
typedef TCoClassCreatorT<TCOMITest117Server, ITest117Server, &CLSID_Test117Server, &IID_ITest117Server> CoTest117Server;
#endif  //   __TLB_NO_INTERFACE_WRAPPERS


};     // namespace Project11_7_tlb

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Project11_7_tlb;
#endif

#pragma option pop

#endif // Project11_7_TLBH
