// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : $Revision:   1.151.1.0.1.27  $
// File generated on 2002-11-21 15:59:02 from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\Program Files\CBuilder6Example\Charp16\Project16_1.tlb (1)
// LIBID: {1D85EAFB-ED22-4255-927E-29F865F28369}
// LCID: 0
// Helpfile: 
// HelpString: Project16_1 Library
// DepndLst: 
//   (1) v1.0 Midas, (D:\WINNT\System32\midas.dll)
//   (2) v2.0 stdole, (D:\WINNT\System32\stdole2.tlb)
// ************************************************************************ //
#ifndef   Project16_1_TLBH
#define   Project16_1_TLBH

#pragma option push -b -w-inl

#include <utilcls.h>
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0600)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if defined(USING_ATLVCL) || defined(USING_ATL)
#if !defined(__TLB_NO_EVENT_WRAPPERS)
#include <atl/atlmod.h>
#endif
#endif

#include "databkr.hpp"

using Midas::IAppServer;

// *********************************************************************//
// Forward reference of some VCL types (to avoid including STDVCL.HPP)    
// *********************************************************************//
namespace Stdvcl {class IStrings; class IStringsDisp;}
using namespace Stdvcl;
typedef TComInterface<IStrings> IStringsPtr;
typedef TComInterface<IStringsDisp> IStringsDispPtr;

namespace Project16_1_tlb
{

// *********************************************************************//
// HelpString: Project16_1 Library
// Version:    1.0
// *********************************************************************//


// *********************************************************************//
// GUIDS declared in the TypeLibrary. Following prefixes are used:        
//   Type Libraries     : LIBID_xxxx                                      
//   CoClasses          : CLSID_xxxx                                      
//   DISPInterfaces     : DIID_xxxx                                       
//   Non-DISP interfaces: IID_xxxx                                        
// *********************************************************************//
extern "C" const __declspec(selectany) GUID LIBID_Project16_1 = {0x1D85EAFB, 0xED22, 0x4255,{ 0x92, 0x7E, 0x29,0xF8, 0x65, 0xF2,0x83, 0x69} };
extern "C" const __declspec(selectany) GUID IID_IInterExpressSer = {0xB2AE6210, 0x4580, 0x449A,{ 0xA8, 0xA1, 0xE5,0x04, 0xFC, 0x0A,0x47, 0xA4} };
extern "C" const __declspec(selectany) GUID CLSID_InterExpressSer = {0xC72E62C6, 0x61DE, 0x4B1E,{ 0x8A, 0x01, 0x23,0xC2, 0x6C, 0x34,0xA4, 0x2F} };

// *********************************************************************//
// Forward declaration of types defined in TypeLibrary                    
// *********************************************************************//
interface DECLSPEC_UUID("{B2AE6210-4580-449A-A8A1-E504FC0A47A4}") IInterExpressSer;
typedef TComInterface<IInterExpressSer, &IID_IInterExpressSer> IInterExpressSerPtr;


// *********************************************************************//
// Declaration of CoClasses defined in Type Library                       
// (NOTE: Here we map each CoClass to its Default Interface)              
//                                                                        
// The LIBID_OF_ macro(s) map a LIBID_OF_CoClassName to the GUID of this  
// TypeLibrary. It simplifies the updating of macros when CoClass name    
// change.                                                                
// *********************************************************************//

#define LIBID_OF_InterExpressSer (&LIBID_Project16_1)
// *********************************************************************//
// Interface: IInterExpressSer
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {B2AE6210-4580-449A-A8A1-E504FC0A47A4}
// *********************************************************************//
interface IInterExpressSer  : public IAppServer
{
public:
  virtual HRESULT STDMETHODCALLTYPE QueryEmployee(BSTR DEPT_NO/*[in]*/, BSTR FULL_NAME/*[in]*/, 
                                                  VARIANT* ret/*[out,retval]*/) = 0; // [1]
  virtual HRESULT STDMETHODCALLTYPE PostCountry(BSTR INPUT/*[in]*/, VARIANT* ret/*[out,retval]*/) = 0; // [2]
  virtual HRESULT STDMETHODCALLTYPE QueryCountry(VARIANT* ret/*[out,retval]*/) = 0; // [3]

#if !defined(__TLB_NO_INTERFACE_WRAPPERS)

  VARIANT __fastcall QueryEmployee(BSTR DEPT_NO/*[in]*/, BSTR FULL_NAME/*[in]*/)
  {
    VARIANT ret;
    OLECHECK(this->QueryEmployee(DEPT_NO, FULL_NAME, (VARIANT*)&ret));
    return ret;
  }

  VARIANT __fastcall PostCountry(BSTR INPUT/*[in]*/)
  {
    VARIANT ret;
    OLECHECK(this->PostCountry(INPUT, (VARIANT*)&ret));
    return ret;
  }

  VARIANT __fastcall QueryCountry(void)
  {
    VARIANT ret;
    OLECHECK(this->QueryCountry((VARIANT*)&ret));
    return ret;
  }



#endif //   __TLB_NO_INTERFACE_WRAPPERS

};

#if !defined(__TLB_NO_INTERFACE_WRAPPERS)
// *********************************************************************//
// SmartIntf: TCOMIInterExpressSer
// Interface: IInterExpressSer
// *********************************************************************//
template <class T /* IInterExpressSer */ >
class TCOMIInterExpressSerT : public TComInterface<IInterExpressSer>, public TComInterfaceBase<IUnknown>
{
public:
  TCOMIInterExpressSerT() {}
  TCOMIInterExpressSerT(IInterExpressSer *intf, bool addRef = false) : TComInterface<IInterExpressSer>(intf, addRef) {}
  TCOMIInterExpressSerT(const TCOMIInterExpressSerT& src) : TComInterface<IInterExpressSer>(src) {}
  TCOMIInterExpressSerT& operator=(const TCOMIInterExpressSerT& src) { Bind(src, true); return *this;}

  HRESULT         __fastcall QueryEmployee(BSTR DEPT_NO/*[in]*/, BSTR FULL_NAME/*[in]*/, 
                                           VARIANT* ret/*[out,retval]*/);
  VARIANT         __fastcall QueryEmployee(BSTR DEPT_NO/*[in]*/, BSTR FULL_NAME/*[in]*/);
  HRESULT         __fastcall PostCountry(BSTR INPUT/*[in]*/, VARIANT* ret/*[out,retval]*/);
  VARIANT         __fastcall PostCountry(BSTR INPUT/*[in]*/);
  HRESULT         __fastcall QueryCountry(VARIANT* ret/*[out,retval]*/);
  VARIANT         __fastcall QueryCountry(void);

};
typedef TCOMIInterExpressSerT<IInterExpressSer> TCOMIInterExpressSer;

// *********************************************************************//
// DispIntf:  IInterExpressSer
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {B2AE6210-4580-449A-A8A1-E504FC0A47A4}
// *********************************************************************//
template<class T>
class IInterExpressSerDispT : public TAutoDriver<IInterExpressSer>
{
public:
  IInterExpressSerDispT(){}

  IInterExpressSerDispT(IInterExpressSer *pintf)
  {
    TAutoDriver<IInterExpressSer>::Bind(pintf, false);
  }

  IInterExpressSerDispT(IInterExpressSerPtr pintf)
  {
    TAutoDriver<IInterExpressSer>::Bind(pintf, true);
  }

  IInterExpressSerDispT& operator=(IInterExpressSer *pintf)
  {
    TAutoDriver<IInterExpressSer>::Bind(pintf, false);
    return *this;
  }

  IInterExpressSerDispT& operator=(IInterExpressSerPtr pintf)
  {
    TAutoDriver<IInterExpressSer>::Bind(pintf, true);
    return *this;
  }

  HRESULT BindDefault()
  {
    return OLECHECK(Bind(CLSID_InterExpressSer));
  }

  HRESULT BindRunning()
  {
    return BindToActive(CLSID_InterExpressSer);
  }

  HRESULT         __fastcall QueryEmployee(BSTR DEPT_NO/*[in]*/, BSTR FULL_NAME/*[in]*/, 
                                           VARIANT* ret/*[out,retval]*/);
  VARIANT         __fastcall QueryEmployee(BSTR DEPT_NO/*[in]*/, BSTR FULL_NAME/*[in]*/);
  HRESULT         __fastcall PostCountry(BSTR INPUT/*[in]*/, VARIANT* ret/*[out,retval]*/);
  VARIANT         __fastcall PostCountry(BSTR INPUT/*[in]*/);
  HRESULT         __fastcall QueryCountry(VARIANT* ret/*[out,retval]*/);
  VARIANT         __fastcall QueryCountry(void);
  HRESULT         __fastcall AS_ApplyUpdates(BSTR ProviderName/*[in]*/, VARIANT Delta/*[in]*/, 
                                             long MaxErrors/*[in]*/, long* ErrorCount/*[out]*/, 
                                             VARIANT* OwnerData/*[in,out]*/, 
                                             VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall AS_ApplyUpdates(BSTR ProviderName/*[in]*/, VARIANT Delta/*[in]*/, 
                                             long MaxErrors/*[in]*/, long* ErrorCount/*[out]*/, 
                                             VARIANT* OwnerData/*[in,out]*/);
  HRESULT         __fastcall AS_GetRecords(BSTR ProviderName/*[in]*/, long Count/*[in]*/, 
                                           long* RecsOut/*[out]*/, long Options/*[in]*/, 
                                           BSTR CommandText/*[in]*/, VARIANT* Params/*[in,out]*/, 
                                           VARIANT* OwnerData/*[in,out]*/, 
                                           VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall AS_GetRecords(BSTR ProviderName/*[in]*/, long Count/*[in]*/, 
                                           long* RecsOut/*[out]*/, long Options/*[in]*/, 
                                           BSTR CommandText/*[in]*/, VARIANT* Params/*[in,out]*/, 
                                           VARIANT* OwnerData/*[in,out]*/);
  HRESULT         __fastcall AS_DataRequest(BSTR ProviderName/*[in]*/, VARIANT Data/*[in]*/, 
                                            VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall AS_DataRequest(BSTR ProviderName/*[in]*/, VARIANT Data/*[in]*/);
  HRESULT         __fastcall AS_GetProviderNames(VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall AS_GetProviderNames(void);
  HRESULT         __fastcall AS_GetParams(BSTR ProviderName/*[in]*/, VARIANT* OwnerData/*[in,out]*/
                                          , VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall AS_GetParams(BSTR ProviderName/*[in]*/, VARIANT* OwnerData/*[in,out]*/);
  HRESULT         __fastcall AS_RowRequest(BSTR ProviderName/*[in]*/, VARIANT Row/*[in]*/, 
                                           long RequestType/*[in]*/, VARIANT* OwnerData/*[in,out]*/
                                           , VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall AS_RowRequest(BSTR ProviderName/*[in]*/, VARIANT Row/*[in]*/, 
                                           long RequestType/*[in]*/, VARIANT* OwnerData/*[in,out]*/);
  HRESULT         __fastcall AS_Execute(BSTR ProviderName/*[in]*/, BSTR CommandText/*[in]*/, 
                                        VARIANT* Params/*[in,out]*/, VARIANT* OwnerData/*[in,out]*/);


};
typedef IInterExpressSerDispT<IInterExpressSer> IInterExpressSerDisp;

// *********************************************************************//
// SmartIntf: TCOMIInterExpressSer
// Interface: IInterExpressSer
// *********************************************************************//
template <class T> HRESULT __fastcall
TCOMIInterExpressSerT<T>::QueryEmployee(BSTR DEPT_NO/*[in]*/, BSTR FULL_NAME/*[in]*/, 
                                        VARIANT* ret/*[out,retval]*/)
{
  return (*this)->QueryEmployee(DEPT_NO, FULL_NAME, ret);
}

template <class T> VARIANT __fastcall
TCOMIInterExpressSerT<T>::QueryEmployee(BSTR DEPT_NO/*[in]*/, BSTR FULL_NAME/*[in]*/)
{
  VARIANT ret;
  OLECHECK(this->QueryEmployee(, (VARIANT*)&ret));
  return ret;
}

template <class T> HRESULT __fastcall
TCOMIInterExpressSerT<T>::PostCountry(BSTR INPUT/*[in]*/, VARIANT* ret/*[out,retval]*/)
{
  return (*this)->PostCountry(INPUT, ret);
}

template <class T> VARIANT __fastcall
TCOMIInterExpressSerT<T>::PostCountry(BSTR INPUT/*[in]*/)
{
  VARIANT ret;
  OLECHECK(this->PostCountry(, (VARIANT*)&ret));
  return ret;
}

template <class T> HRESULT __fastcall
TCOMIInterExpressSerT<T>::QueryCountry(VARIANT* ret/*[out,retval]*/)
{
  return (*this)->QueryCountry(ret);
}

template <class T> VARIANT __fastcall
TCOMIInterExpressSerT<T>::QueryCountry(void)
{
  VARIANT ret;
  OLECHECK(this->QueryCountry((VARIANT*)&ret));
  return ret;
}

// *********************************************************************//
// DispIntf:  IInterExpressSer
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {B2AE6210-4580-449A-A8A1-E504FC0A47A4}
// *********************************************************************//
template <class T> HRESULT __fastcall
IInterExpressSerDispT<T>::QueryEmployee(BSTR DEPT_NO/*[in]*/, BSTR FULL_NAME/*[in]*/, 
                                        VARIANT* ret/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("QueryEmployee"), DISPID(1));
  TAutoArgs<2> _args;
  _args[1] = DEPT_NO /*[VT_BSTR:0]*/;
  _args[2] = FULL_NAME /*[VT_BSTR:0]*/;
  return OutRetValSetterPtr(ret /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
IInterExpressSerDispT<T>::QueryEmployee(BSTR DEPT_NO/*[in]*/, BSTR FULL_NAME/*[in]*/)
{
  VARIANT ret;
  this->QueryEmployee(DEPT_NO, FULL_NAME, (VARIANT*)&ret);
  return ret;
}

template <class T> HRESULT __fastcall
IInterExpressSerDispT<T>::PostCountry(BSTR INPUT/*[in]*/, VARIANT* ret/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("PostCountry"), DISPID(2));
  TAutoArgs<1> _args;
  _args[1] = INPUT /*[VT_BSTR:0]*/;
  return OutRetValSetterPtr(ret /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
IInterExpressSerDispT<T>::PostCountry(BSTR INPUT/*[in]*/)
{
  VARIANT ret;
  this->PostCountry(INPUT, (VARIANT*)&ret);
  return ret;
}

template <class T> HRESULT __fastcall
IInterExpressSerDispT<T>::QueryCountry(VARIANT* ret/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("QueryCountry"), DISPID(3));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(ret /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
IInterExpressSerDispT<T>::QueryCountry(void)
{
  VARIANT ret;
  this->QueryCountry((VARIANT*)&ret);
  return ret;
}

template <class T> HRESULT __fastcall
IInterExpressSerDispT<T>::AS_ApplyUpdates(BSTR ProviderName/*[in]*/, VARIANT Delta/*[in]*/, 
                                          long MaxErrors/*[in]*/, long* ErrorCount/*[out]*/, 
                                          VARIANT* OwnerData/*[in,out]*/, 
                                          VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_ApplyUpdates"), DISPID(20000000));
  TAutoArgs<5> _args;
  _args[1] = ProviderName /*[VT_BSTR:0]*/;
  _args[2] = Delta /*[VT_VARIANT:0]*/;
  _args[3] = MaxErrors /*[VT_I4:0]*/;
  _args[4] = ErrorCount /*[VT_I4:1]*/;
  _args[5] = OwnerData /*[VT_VARIANT:1]*/;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
IInterExpressSerDispT<T>::AS_ApplyUpdates(BSTR ProviderName/*[in]*/, VARIANT Delta/*[in]*/, 
                                          long MaxErrors/*[in]*/, long* ErrorCount/*[out]*/, 
                                          VARIANT* OwnerData/*[in,out]*/)
{
  VARIANT Value;
  this->AS_ApplyUpdates(ProviderName, Delta, MaxErrors, ErrorCount, OwnerData, (VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IInterExpressSerDispT<T>::AS_GetRecords(BSTR ProviderName/*[in]*/, long Count/*[in]*/, 
                                        long* RecsOut/*[out]*/, long Options/*[in]*/, 
                                        BSTR CommandText/*[in]*/, VARIANT* Params/*[in,out]*/, 
                                        VARIANT* OwnerData/*[in,out]*/, 
                                        VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_GetRecords"), DISPID(20000001));
  TAutoArgs<7> _args;
  _args[1] = ProviderName /*[VT_BSTR:0]*/;
  _args[2] = Count /*[VT_I4:0]*/;
  _args[3] = RecsOut /*[VT_I4:1]*/;
  _args[4] = Options /*[VT_I4:0]*/;
  _args[5] = CommandText /*[VT_BSTR:0]*/;
  _args[6] = Params /*[VT_VARIANT:1]*/;
  _args[7] = OwnerData /*[VT_VARIANT:1]*/;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
IInterExpressSerDispT<T>::AS_GetRecords(BSTR ProviderName/*[in]*/, long Count/*[in]*/, 
                                        long* RecsOut/*[out]*/, long Options/*[in]*/, 
                                        BSTR CommandText/*[in]*/, VARIANT* Params/*[in,out]*/, 
                                        VARIANT* OwnerData/*[in,out]*/)
{
  VARIANT Value;
  this->AS_GetRecords(ProviderName, Count, RecsOut, Options, CommandText, Params, OwnerData, (VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IInterExpressSerDispT<T>::AS_DataRequest(BSTR ProviderName/*[in]*/, VARIANT Data/*[in]*/, 
                                         VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_DataRequest"), DISPID(20000002));
  TAutoArgs<2> _args;
  _args[1] = ProviderName /*[VT_BSTR:0]*/;
  _args[2] = Data /*[VT_VARIANT:0]*/;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
IInterExpressSerDispT<T>::AS_DataRequest(BSTR ProviderName/*[in]*/, VARIANT Data/*[in]*/)
{
  VARIANT Value;
  this->AS_DataRequest(ProviderName, Data, (VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IInterExpressSerDispT<T>::AS_GetProviderNames(VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_GetProviderNames"), DISPID(20000003));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
IInterExpressSerDispT<T>::AS_GetProviderNames(void)
{
  VARIANT Value;
  this->AS_GetProviderNames((VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IInterExpressSerDispT<T>::AS_GetParams(BSTR ProviderName/*[in]*/, VARIANT* OwnerData/*[in,out]*/, 
                                       VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_GetParams"), DISPID(20000004));
  TAutoArgs<2> _args;
  _args[1] = ProviderName /*[VT_BSTR:0]*/;
  _args[2] = OwnerData /*[VT_VARIANT:1]*/;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
IInterExpressSerDispT<T>::AS_GetParams(BSTR ProviderName/*[in]*/, VARIANT* OwnerData/*[in,out]*/)
{
  VARIANT Value;
  this->AS_GetParams(ProviderName, OwnerData, (VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IInterExpressSerDispT<T>::AS_RowRequest(BSTR ProviderName/*[in]*/, VARIANT Row/*[in]*/, 
                                        long RequestType/*[in]*/, VARIANT* OwnerData/*[in,out]*/, 
                                        VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_RowRequest"), DISPID(20000005));
  TAutoArgs<4> _args;
  _args[1] = ProviderName /*[VT_BSTR:0]*/;
  _args[2] = Row /*[VT_VARIANT:0]*/;
  _args[3] = RequestType /*[VT_I4:0]*/;
  _args[4] = OwnerData /*[VT_VARIANT:1]*/;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
IInterExpressSerDispT<T>::AS_RowRequest(BSTR ProviderName/*[in]*/, VARIANT Row/*[in]*/, 
                                        long RequestType/*[in]*/, VARIANT* OwnerData/*[in,out]*/)
{
  VARIANT Value;
  this->AS_RowRequest(ProviderName, Row, RequestType, OwnerData, (VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
IInterExpressSerDispT<T>::AS_Execute(BSTR ProviderName/*[in]*/, BSTR CommandText/*[in]*/, 
                                     VARIANT* Params/*[in,out]*/, VARIANT* OwnerData/*[in,out]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_Execute"), DISPID(20000006));
  TAutoArgs<4> _args;
  _args[1] = ProviderName /*[VT_BSTR:0]*/;
  _args[2] = CommandText /*[VT_BSTR:0]*/;
  _args[3] = Params /*[VT_VARIANT:1]*/;
  _args[4] = OwnerData /*[VT_VARIANT:1]*/;
  return OleFunction(_dispid, _args);
}

// *********************************************************************//
// The following typedefs expose classes (named CoCoClassName) that       
// provide static Create() and CreateRemote(LPWSTR machineName) methods   
// for creating an instance of an exposed object. These functions can     
// be used by client wishing to automate CoClasses exposed by this        
// typelibrary.                                                           
// *********************************************************************//

// *********************************************************************//
// COCLASS DEFAULT INTERFACE CREATOR
// CoClass  : InterExpressSer
// Interface: TCOMIInterExpressSer
// *********************************************************************//
typedef TCoClassCreatorT<TCOMIInterExpressSer, IInterExpressSer, &CLSID_InterExpressSer, &IID_IInterExpressSer> CoInterExpressSer;
#endif  //   __TLB_NO_INTERFACE_WRAPPERS


};     // namespace Project16_1_tlb

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Project16_1_tlb;
#endif

#pragma option pop

#endif // Project16_1_TLBH
