// Do not edit. This file is machine generated by the Resource DLL Wizard.
//---------------------------------------------------------------------------
#define PACKAGE __declspec(package)
#define USERC(FileName) extern PACKAGE _Dummy
#define USERES(FileName) extern PACKAGE _Dummy
#define USEFORMRES(FileName, FormName, AncestorName) extern PACKAGE _Dummy
#pragma hdrstop
int _turboFloat;
//---------------------------------------------------------------------------
/*ITE*/ /*LCID:00000404:00000409*/ /**/
/*ITE*/ /*DFMFileType*/ /*Unit7_9.dfm*/
/*ITE*/ /*RCFileType*/ /*Project7_9_DRC.rc*/
//---------------------------------------------------------------------------
USEFORMRES("Unit7_9.dfm", Form1, Form); /* TForm: DesignClass */
#pragma resource "Unit7_9.dfm"
USERC("Project7_9_DRC.rc");
//---------------------------------------------------------------------------
#define DllEntryPoint
