// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : $Revision:   1.151.1.0.1.27  $
// File generated on 2002-11-20 18:17:50 from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\Program Files\CBuilder6Example\Charp12\Project12_5.tlb (1)
// LIBID: {B403C62B-1CBF-11D4-958C-0080C85400DC}
// LCID: 0
// Helpfile: 
// HelpString: Project1 Library
// DepndLst: 
//   (1) v1.0 Midas, (D:\WINNT\System32\midas.dll)
//   (2) v2.0 stdole, (D:\WINNT\System32\stdole2.tlb)
// ************************************************************************ //
#ifndef   Project12_5_TLBH
#define   Project12_5_TLBH

#pragma option push -b -w-inl

#include <utilcls.h>
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0600)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if defined(USING_ATLVCL) || defined(USING_ATL)
#if !defined(__TLB_NO_EVENT_WRAPPERS)
#include <atl/atlmod.h>
#endif
#endif

#include "databkr.hpp"

using Midas::IAppServer;

// *********************************************************************//
// Forward reference of some VCL types (to avoid including STDVCL.HPP)    
// *********************************************************************//
namespace Stdvcl {class IStrings; class IStringsDisp;}
using namespace Stdvcl;
typedef TComInterface<IStrings> IStringsPtr;
typedef TComInterface<IStringsDisp> IStringsDispPtr;

namespace Project12_5_tlb
{

// *********************************************************************//
// HelpString: Project1 Library
// Version:    1.0
// *********************************************************************//


// *********************************************************************//
// GUIDS declared in the TypeLibrary. Following prefixes are used:        
//   Type Libraries     : LIBID_xxxx                                      
//   CoClasses          : CLSID_xxxx                                      
//   DISPInterfaces     : DIID_xxxx                                       
//   Non-DISP interfaces: IID_xxxx                                        
// *********************************************************************//
extern "C" const __declspec(selectany) GUID LIBID_Project12_5 = {0xB403C62B, 0x1CBF, 0x11D4,{ 0x95, 0x8C, 0x00,0x80, 0xC8, 0x54,0x00, 0xDC} };
extern "C" const __declspec(selectany) GUID IID_ITest125Server = {0xB403C62C, 0x1CBF, 0x11D4,{ 0x95, 0x8C, 0x00,0x80, 0xC8, 0x54,0x00, 0xDC} };
extern "C" const __declspec(selectany) GUID CLSID_Test125Server = {0xB403C62E, 0x1CBF, 0x11D4,{ 0x95, 0x8C, 0x00,0x80, 0xC8, 0x54,0x00, 0xDC} };

// *********************************************************************//
// Forward declaration of types defined in TypeLibrary                    
// *********************************************************************//
interface DECLSPEC_UUID("{B403C62C-1CBF-11D4-958C-0080C85400DC}") ITest125Server;
typedef TComInterface<ITest125Server, &IID_ITest125Server> ITest125ServerPtr;


// *********************************************************************//
// Declaration of CoClasses defined in Type Library                       
// (NOTE: Here we map each CoClass to its Default Interface)              
//                                                                        
// The LIBID_OF_ macro(s) map a LIBID_OF_CoClassName to the GUID of this  
// TypeLibrary. It simplifies the updating of macros when CoClass name    
// change.                                                                
// *********************************************************************//

#define LIBID_OF_Test125Server (&LIBID_Project12_5)
// *********************************************************************//
// Interface: ITest125Server
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {B403C62C-1CBF-11D4-958C-0080C85400DC}
// *********************************************************************//
interface ITest125Server  : public IAppServer
{
public:
  virtual HRESULT STDMETHODCALLTYPE Login(BSTR Username/*[in]*/, BSTR Password/*[in]*/, 
                                          VARIANT* Ret/*[out,retval]*/) = 0; // [1]

#if !defined(__TLB_NO_INTERFACE_WRAPPERS)

  VARIANT __fastcall Login(BSTR Username/*[in]*/, BSTR Password/*[in]*/)
  {
    VARIANT Ret;
    OLECHECK(this->Login(Username, Password, (VARIANT*)&Ret));
    return Ret;
  }



#endif //   __TLB_NO_INTERFACE_WRAPPERS

};

#if !defined(__TLB_NO_INTERFACE_WRAPPERS)
// *********************************************************************//
// SmartIntf: TCOMITest125Server
// Interface: ITest125Server
// *********************************************************************//
template <class T /* ITest125Server */ >
class TCOMITest125ServerT : public TComInterface<ITest125Server>, public TComInterfaceBase<IUnknown>
{
public:
  TCOMITest125ServerT() {}
  TCOMITest125ServerT(ITest125Server *intf, bool addRef = false) : TComInterface<ITest125Server>(intf, addRef) {}
  TCOMITest125ServerT(const TCOMITest125ServerT& src) : TComInterface<ITest125Server>(src) {}
  TCOMITest125ServerT& operator=(const TCOMITest125ServerT& src) { Bind(src, true); return *this;}

  HRESULT         __fastcall Login(BSTR Username/*[in]*/, BSTR Password/*[in]*/, 
                                   VARIANT* Ret/*[out,retval]*/);
  VARIANT         __fastcall Login(BSTR Username/*[in]*/, BSTR Password/*[in]*/);

};
typedef TCOMITest125ServerT<ITest125Server> TCOMITest125Server;

// *********************************************************************//
// DispIntf:  ITest125Server
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {B403C62C-1CBF-11D4-958C-0080C85400DC}
// *********************************************************************//
template<class T>
class ITest125ServerDispT : public TAutoDriver<ITest125Server>
{
public:
  ITest125ServerDispT(){}

  ITest125ServerDispT(ITest125Server *pintf)
  {
    TAutoDriver<ITest125Server>::Bind(pintf, false);
  }

  ITest125ServerDispT(ITest125ServerPtr pintf)
  {
    TAutoDriver<ITest125Server>::Bind(pintf, true);
  }

  ITest125ServerDispT& operator=(ITest125Server *pintf)
  {
    TAutoDriver<ITest125Server>::Bind(pintf, false);
    return *this;
  }

  ITest125ServerDispT& operator=(ITest125ServerPtr pintf)
  {
    TAutoDriver<ITest125Server>::Bind(pintf, true);
    return *this;
  }

  HRESULT BindDefault()
  {
    return OLECHECK(Bind(CLSID_Test125Server));
  }

  HRESULT BindRunning()
  {
    return BindToActive(CLSID_Test125Server);
  }

  HRESULT         __fastcall Login(BSTR Username/*[in]*/, BSTR Password/*[in]*/, 
                                   VARIANT* Ret/*[out,retval]*/);
  VARIANT         __fastcall Login(BSTR Username/*[in]*/, BSTR Password/*[in]*/);
  HRESULT         __fastcall AS_ApplyUpdates(BSTR ProviderName/*[in]*/, VARIANT Delta/*[in]*/, 
                                             long MaxErrors/*[in]*/, long* ErrorCount/*[out]*/, 
                                             VARIANT* OwnerData/*[in,out]*/, 
                                             VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall AS_ApplyUpdates(BSTR ProviderName/*[in]*/, VARIANT Delta/*[in]*/, 
                                             long MaxErrors/*[in]*/, long* ErrorCount/*[out]*/, 
                                             VARIANT* OwnerData/*[in,out]*/);
  HRESULT         __fastcall AS_GetRecords(BSTR ProviderName/*[in]*/, long Count/*[in]*/, 
                                           long* RecsOut/*[out]*/, long Options/*[in]*/, 
                                           BSTR CommandText/*[in]*/, VARIANT* Params/*[in,out]*/, 
                                           VARIANT* OwnerData/*[in,out]*/, 
                                           VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall AS_GetRecords(BSTR ProviderName/*[in]*/, long Count/*[in]*/, 
                                           long* RecsOut/*[out]*/, long Options/*[in]*/, 
                                           BSTR CommandText/*[in]*/, VARIANT* Params/*[in,out]*/, 
                                           VARIANT* OwnerData/*[in,out]*/);
  HRESULT         __fastcall AS_DataRequest(BSTR ProviderName/*[in]*/, VARIANT Data/*[in]*/, 
                                            VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall AS_DataRequest(BSTR ProviderName/*[in]*/, VARIANT Data/*[in]*/);
  HRESULT         __fastcall AS_GetProviderNames(VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall AS_GetProviderNames(void);
  HRESULT         __fastcall AS_GetParams(BSTR ProviderName/*[in]*/, VARIANT* OwnerData/*[in,out]*/
                                          , VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall AS_GetParams(BSTR ProviderName/*[in]*/, VARIANT* OwnerData/*[in,out]*/);
  HRESULT         __fastcall AS_RowRequest(BSTR ProviderName/*[in]*/, VARIANT Row/*[in]*/, 
                                           long RequestType/*[in]*/, VARIANT* OwnerData/*[in,out]*/
                                           , VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall AS_RowRequest(BSTR ProviderName/*[in]*/, VARIANT Row/*[in]*/, 
                                           long RequestType/*[in]*/, VARIANT* OwnerData/*[in,out]*/);
  HRESULT         __fastcall AS_Execute(BSTR ProviderName/*[in]*/, BSTR CommandText/*[in]*/, 
                                        VARIANT* Params/*[in,out]*/, VARIANT* OwnerData/*[in,out]*/);


};
typedef ITest125ServerDispT<ITest125Server> ITest125ServerDisp;

// *********************************************************************//
// SmartIntf: TCOMITest125Server
// Interface: ITest125Server
// *********************************************************************//
template <class T> HRESULT __fastcall
TCOMITest125ServerT<T>::Login(BSTR Username/*[in]*/, BSTR Password/*[in]*/, 
                              VARIANT* Ret/*[out,retval]*/)
{
  return (*this)->Login(Username, Password, Ret);
}

template <class T> VARIANT __fastcall
TCOMITest125ServerT<T>::Login(BSTR Username/*[in]*/, BSTR Password/*[in]*/)
{
  VARIANT Ret;
  OLECHECK(this->Login(, (VARIANT*)&Ret));
  return Ret;
}

// *********************************************************************//
// DispIntf:  ITest125Server
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {B403C62C-1CBF-11D4-958C-0080C85400DC}
// *********************************************************************//
template <class T> HRESULT __fastcall
ITest125ServerDispT<T>::Login(BSTR Username/*[in]*/, BSTR Password/*[in]*/, 
                              VARIANT* Ret/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("Login"), DISPID(1));
  TAutoArgs<2> _args;
  _args[1] = Username /*[VT_BSTR:0]*/;
  _args[2] = Password /*[VT_BSTR:0]*/;
  return OutRetValSetterPtr(Ret /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
ITest125ServerDispT<T>::Login(BSTR Username/*[in]*/, BSTR Password/*[in]*/)
{
  VARIANT Ret;
  this->Login(Username, Password, (VARIANT*)&Ret);
  return Ret;
}

template <class T> HRESULT __fastcall
ITest125ServerDispT<T>::AS_ApplyUpdates(BSTR ProviderName/*[in]*/, VARIANT Delta/*[in]*/, 
                                        long MaxErrors/*[in]*/, long* ErrorCount/*[out]*/, 
                                        VARIANT* OwnerData/*[in,out]*/, 
                                        VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_ApplyUpdates"), DISPID(20000000));
  TAutoArgs<5> _args;
  _args[1] = ProviderName /*[VT_BSTR:0]*/;
  _args[2] = Delta /*[VT_VARIANT:0]*/;
  _args[3] = MaxErrors /*[VT_I4:0]*/;
  _args[4] = ErrorCount /*[VT_I4:1]*/;
  _args[5] = OwnerData /*[VT_VARIANT:1]*/;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
ITest125ServerDispT<T>::AS_ApplyUpdates(BSTR ProviderName/*[in]*/, VARIANT Delta/*[in]*/, 
                                        long MaxErrors/*[in]*/, long* ErrorCount/*[out]*/, 
                                        VARIANT* OwnerData/*[in,out]*/)
{
  VARIANT Value;
  this->AS_ApplyUpdates(ProviderName, Delta, MaxErrors, ErrorCount, OwnerData, (VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITest125ServerDispT<T>::AS_GetRecords(BSTR ProviderName/*[in]*/, long Count/*[in]*/, 
                                      long* RecsOut/*[out]*/, long Options/*[in]*/, 
                                      BSTR CommandText/*[in]*/, VARIANT* Params/*[in,out]*/, 
                                      VARIANT* OwnerData/*[in,out]*/, VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_GetRecords"), DISPID(20000001));
  TAutoArgs<7> _args;
  _args[1] = ProviderName /*[VT_BSTR:0]*/;
  _args[2] = Count /*[VT_I4:0]*/;
  _args[3] = RecsOut /*[VT_I4:1]*/;
  _args[4] = Options /*[VT_I4:0]*/;
  _args[5] = CommandText /*[VT_BSTR:0]*/;
  _args[6] = Params /*[VT_VARIANT:1]*/;
  _args[7] = OwnerData /*[VT_VARIANT:1]*/;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
ITest125ServerDispT<T>::AS_GetRecords(BSTR ProviderName/*[in]*/, long Count/*[in]*/, 
                                      long* RecsOut/*[out]*/, long Options/*[in]*/, 
                                      BSTR CommandText/*[in]*/, VARIANT* Params/*[in,out]*/, 
                                      VARIANT* OwnerData/*[in,out]*/)
{
  VARIANT Value;
  this->AS_GetRecords(ProviderName, Count, RecsOut, Options, CommandText, Params, OwnerData, (VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITest125ServerDispT<T>::AS_DataRequest(BSTR ProviderName/*[in]*/, VARIANT Data/*[in]*/, 
                                       VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_DataRequest"), DISPID(20000002));
  TAutoArgs<2> _args;
  _args[1] = ProviderName /*[VT_BSTR:0]*/;
  _args[2] = Data /*[VT_VARIANT:0]*/;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
ITest125ServerDispT<T>::AS_DataRequest(BSTR ProviderName/*[in]*/, VARIANT Data/*[in]*/)
{
  VARIANT Value;
  this->AS_DataRequest(ProviderName, Data, (VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITest125ServerDispT<T>::AS_GetProviderNames(VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_GetProviderNames"), DISPID(20000003));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
ITest125ServerDispT<T>::AS_GetProviderNames(void)
{
  VARIANT Value;
  this->AS_GetProviderNames((VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITest125ServerDispT<T>::AS_GetParams(BSTR ProviderName/*[in]*/, VARIANT* OwnerData/*[in,out]*/, 
                                     VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_GetParams"), DISPID(20000004));
  TAutoArgs<2> _args;
  _args[1] = ProviderName /*[VT_BSTR:0]*/;
  _args[2] = OwnerData /*[VT_VARIANT:1]*/;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
ITest125ServerDispT<T>::AS_GetParams(BSTR ProviderName/*[in]*/, VARIANT* OwnerData/*[in,out]*/)
{
  VARIANT Value;
  this->AS_GetParams(ProviderName, OwnerData, (VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITest125ServerDispT<T>::AS_RowRequest(BSTR ProviderName/*[in]*/, VARIANT Row/*[in]*/, 
                                      long RequestType/*[in]*/, VARIANT* OwnerData/*[in,out]*/, 
                                      VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_RowRequest"), DISPID(20000005));
  TAutoArgs<4> _args;
  _args[1] = ProviderName /*[VT_BSTR:0]*/;
  _args[2] = Row /*[VT_VARIANT:0]*/;
  _args[3] = RequestType /*[VT_I4:0]*/;
  _args[4] = OwnerData /*[VT_VARIANT:1]*/;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
ITest125ServerDispT<T>::AS_RowRequest(BSTR ProviderName/*[in]*/, VARIANT Row/*[in]*/, 
                                      long RequestType/*[in]*/, VARIANT* OwnerData/*[in,out]*/)
{
  VARIANT Value;
  this->AS_RowRequest(ProviderName, Row, RequestType, OwnerData, (VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITest125ServerDispT<T>::AS_Execute(BSTR ProviderName/*[in]*/, BSTR CommandText/*[in]*/, 
                                   VARIANT* Params/*[in,out]*/, VARIANT* OwnerData/*[in,out]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_Execute"), DISPID(20000006));
  TAutoArgs<4> _args;
  _args[1] = ProviderName /*[VT_BSTR:0]*/;
  _args[2] = CommandText /*[VT_BSTR:0]*/;
  _args[3] = Params /*[VT_VARIANT:1]*/;
  _args[4] = OwnerData /*[VT_VARIANT:1]*/;
  return OleFunction(_dispid, _args);
}

// *********************************************************************//
// The following typedefs expose classes (named CoCoClassName) that       
// provide static Create() and CreateRemote(LPWSTR machineName) methods   
// for creating an instance of an exposed object. These functions can     
// be used by client wishing to automate CoClasses exposed by this        
// typelibrary.                                                           
// *********************************************************************//

// *********************************************************************//
// COCLASS DEFAULT INTERFACE CREATOR
// CoClass  : Test125Server
// Interface: TCOMITest125Server
// *********************************************************************//
typedef TCoClassCreatorT<TCOMITest125Server, ITest125Server, &CLSID_Test125Server, &IID_ITest125Server> CoTest125Server;
#endif  //   __TLB_NO_INTERFACE_WRAPPERS


};     // namespace Project12_5_tlb

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Project12_5_tlb;
#endif

#pragma option pop

#endif // Project12_5_TLBH
