// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : $Revision:   1.151.1.0.1.27  $
// File generated on 2002/6/4 ¤W¤È 08:25:56 from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\Paul\CBuilder6\Example\Charp12\Project12_a.tlb (1)
// LIBID: {22993030-2167-11D4-9592-0080C85400DC}
// LCID: 0
// Helpfile: 
// HelpString: Project2 Library
// DepndLst: 
//   (1) v1.0 Midas, (C:\WINNT\System32\midas.dll)
//   (2) v2.0 stdole, (C:\WINNT\System32\stdole2.tlb)
// ************************************************************************ //
#ifndef   Project13b_TLBH
#define   Project13b_TLBH

#pragma option push -b -w-inl

#include <utilcls.h>
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0600)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if defined(USING_ATLVCL) || defined(USING_ATL)
#if !defined(__TLB_NO_EVENT_WRAPPERS)
#include <atl/atlmod.h>
#endif
#endif

#include "databkr.hpp"

using Midas::IAppServer;

// *********************************************************************//
// Forward reference of some VCL types (to avoid including STDVCL.HPP)    
// *********************************************************************//
namespace Stdvcl {class IStrings; class IStringsDisp;}
using namespace Stdvcl;
typedef TComInterface<IStrings> IStringsPtr;
typedef TComInterface<IStringsDisp> IStringsDispPtr;

namespace Project13b_tlb
{

// *********************************************************************//
// HelpString: Project2 Library
// Version:    1.0
// *********************************************************************//


// *********************************************************************//
// GUIDS declared in the TypeLibrary. Following prefixes are used:        
//   Type Libraries     : LIBID_xxxx                                      
//   CoClasses          : CLSID_xxxx                                      
//   DISPInterfaces     : DIID_xxxx                                       
//   Non-DISP interfaces: IID_xxxx                                        
// *********************************************************************//
extern "C" const __declspec(selectany) GUID LIBID_Project13b = {0x22993030, 0x2167, 0x11D4,{ 0x95, 0x92, 0x00,0x80, 0xC8, 0x54,0x00, 0xDC} };
extern "C" const __declspec(selectany) GUID IID_ITest13bServer = {0x22993031, 0x2167, 0x11D4,{ 0x95, 0x92, 0x00,0x80, 0xC8, 0x54,0x00, 0xDC} };
extern "C" const __declspec(selectany) GUID CLSID_Test12aServer = {0x22993033, 0x2167, 0x11D4,{ 0x95, 0x92, 0x00,0x80, 0xC8, 0x54,0x00, 0xDC} };

// *********************************************************************//
// Forward declaration of types defined in TypeLibrary                    
// *********************************************************************//
interface DECLSPEC_UUID("{22993031-2167-11D4-9592-0080C85400DC}") ITest13bServer;
typedef TComInterface<ITest13bServer, &IID_ITest13bServer> ITest13bServerPtr;


// *********************************************************************//
// Declaration of CoClasses defined in Type Library                       
// (NOTE: Here we map each CoClass to its Default Interface)              
//                                                                        
// The LIBID_OF_ macro(s) map a LIBID_OF_CoClassName to the GUID of this  
// TypeLibrary. It simplifies the updating of macros when CoClass name    
// change.                                                                
// *********************************************************************//

#define LIBID_OF_Test12aServer (&LIBID_Project13b)
// *********************************************************************//
// Interface: ITest13bServer
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {22993031-2167-11D4-9592-0080C85400DC}
// *********************************************************************//
interface ITest13bServer  : public IAppServer
{
public:
  virtual HRESULT STDMETHODCALLTYPE GetName(VARIANT* Ret/*[out,retval]*/) = 0; // [1]

#if !defined(__TLB_NO_INTERFACE_WRAPPERS)

  VARIANT __fastcall GetName(void)
  {
    VARIANT Ret;
    OLECHECK(this->GetName((VARIANT*)&Ret));
    return Ret;
  }



#endif //   __TLB_NO_INTERFACE_WRAPPERS

};

#if !defined(__TLB_NO_INTERFACE_WRAPPERS)
// *********************************************************************//
// SmartIntf: TCOMITest13bServer
// Interface: ITest13bServer
// *********************************************************************//
template <class T /* ITest13bServer */ >
class TCOMITest13bServerT : public TComInterface<ITest13bServer>, public TComInterfaceBase<IUnknown>
{
public:
  TCOMITest13bServerT() {}
  TCOMITest13bServerT(ITest13bServer *intf, bool addRef = false) : TComInterface<ITest13bServer>(intf, addRef) {}
  TCOMITest13bServerT(const TCOMITest13bServerT& src) : TComInterface<ITest13bServer>(src) {}
  TCOMITest13bServerT& operator=(const TCOMITest13bServerT& src) { Bind(src, true); return *this;}

  HRESULT         __fastcall GetName(VARIANT* Ret/*[out,retval]*/);
  VARIANT         __fastcall GetName(void);

};
typedef TCOMITest13bServerT<ITest13bServer> TCOMITest13bServer;

// *********************************************************************//
// DispIntf:  ITest13bServer
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {22993031-2167-11D4-9592-0080C85400DC}
// *********************************************************************//
template<class T>
class ITest13bServerDispT : public TAutoDriver<ITest13bServer>
{
public:
  ITest13bServerDispT(){}

  ITest13bServerDispT(ITest13bServer *pintf)
  {
    TAutoDriver<ITest13bServer>::Bind(pintf, false);
  }

  ITest13bServerDispT(ITest13bServerPtr pintf)
  {
    TAutoDriver<ITest13bServer>::Bind(pintf, true);
  }

  ITest13bServerDispT& operator=(ITest13bServer *pintf)
  {
    TAutoDriver<ITest13bServer>::Bind(pintf, false);
    return *this;
  }

  ITest13bServerDispT& operator=(ITest13bServerPtr pintf)
  {
    TAutoDriver<ITest13bServer>::Bind(pintf, true);
    return *this;
  }

  HRESULT BindDefault()
  {
    return OLECHECK(Bind(CLSID_Test12aServer));
  }

  HRESULT BindRunning()
  {
    return BindToActive(CLSID_Test12aServer);
  }

  HRESULT         __fastcall GetName(VARIANT* Ret/*[out,retval]*/);
  VARIANT         __fastcall GetName(void);
  HRESULT         __fastcall AS_ApplyUpdates(BSTR ProviderName/*[in]*/, VARIANT Delta/*[in]*/, 
                                             long MaxErrors/*[in]*/, long* ErrorCount/*[out]*/, 
                                             VARIANT* OwnerData/*[in,out]*/, 
                                             VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall AS_ApplyUpdates(BSTR ProviderName/*[in]*/, VARIANT Delta/*[in]*/, 
                                             long MaxErrors/*[in]*/, long* ErrorCount/*[out]*/, 
                                             VARIANT* OwnerData/*[in,out]*/);
  HRESULT         __fastcall AS_GetRecords(BSTR ProviderName/*[in]*/, long Count/*[in]*/, 
                                           long* RecsOut/*[out]*/, long Options/*[in]*/, 
                                           BSTR CommandText/*[in]*/, VARIANT* Params/*[in,out]*/, 
                                           VARIANT* OwnerData/*[in,out]*/, 
                                           VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall AS_GetRecords(BSTR ProviderName/*[in]*/, long Count/*[in]*/, 
                                           long* RecsOut/*[out]*/, long Options/*[in]*/, 
                                           BSTR CommandText/*[in]*/, VARIANT* Params/*[in,out]*/, 
                                           VARIANT* OwnerData/*[in,out]*/);
  HRESULT         __fastcall AS_DataRequest(BSTR ProviderName/*[in]*/, VARIANT Data/*[in]*/, 
                                            VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall AS_DataRequest(BSTR ProviderName/*[in]*/, VARIANT Data/*[in]*/);
  HRESULT         __fastcall AS_GetProviderNames(VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall AS_GetProviderNames(void);
  HRESULT         __fastcall AS_GetParams(BSTR ProviderName/*[in]*/, VARIANT* OwnerData/*[in,out]*/
                                          , VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall AS_GetParams(BSTR ProviderName/*[in]*/, VARIANT* OwnerData/*[in,out]*/);
  HRESULT         __fastcall AS_RowRequest(BSTR ProviderName/*[in]*/, VARIANT Row/*[in]*/, 
                                           long RequestType/*[in]*/, VARIANT* OwnerData/*[in,out]*/
                                           , VARIANT* Value/*[out,retval]*/);
  VARIANT         __fastcall AS_RowRequest(BSTR ProviderName/*[in]*/, VARIANT Row/*[in]*/, 
                                           long RequestType/*[in]*/, VARIANT* OwnerData/*[in,out]*/);
  HRESULT         __fastcall AS_Execute(BSTR ProviderName/*[in]*/, BSTR CommandText/*[in]*/, 
                                        VARIANT* Params/*[in,out]*/, VARIANT* OwnerData/*[in,out]*/);


};
typedef ITest13bServerDispT<ITest13bServer> ITest13bServerDisp;

// *********************************************************************//
// SmartIntf: TCOMITest13bServer
// Interface: ITest13bServer
// *********************************************************************//
template <class T> HRESULT __fastcall
TCOMITest13bServerT<T>::GetName(VARIANT* Ret/*[out,retval]*/)
{
  return (*this)->GetName(Ret);
}

template <class T> VARIANT __fastcall
TCOMITest13bServerT<T>::GetName(void)
{
  VARIANT Ret;
  OLECHECK(this->GetName((VARIANT*)&Ret));
  return Ret;
}

// *********************************************************************//
// DispIntf:  ITest13bServer
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {22993031-2167-11D4-9592-0080C85400DC}
// *********************************************************************//
template <class T> HRESULT __fastcall
ITest13bServerDispT<T>::GetName(VARIANT* Ret/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("GetName"), DISPID(1));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Ret /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
ITest13bServerDispT<T>::GetName(void)
{
  VARIANT Ret;
  this->GetName((VARIANT*)&Ret);
  return Ret;
}

template <class T> HRESULT __fastcall
ITest13bServerDispT<T>::AS_ApplyUpdates(BSTR ProviderName/*[in]*/, VARIANT Delta/*[in]*/, 
                                        long MaxErrors/*[in]*/, long* ErrorCount/*[out]*/, 
                                        VARIANT* OwnerData/*[in,out]*/, 
                                        VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_ApplyUpdates"), DISPID(20000000));
  TAutoArgs<5> _args;
  _args[1] = ProviderName /*[VT_BSTR:0]*/;
  _args[2] = Delta /*[VT_VARIANT:0]*/;
  _args[3] = MaxErrors /*[VT_I4:0]*/;
  _args[4] = ErrorCount /*[VT_I4:1]*/;
  _args[5] = OwnerData /*[VT_VARIANT:1]*/;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
ITest13bServerDispT<T>::AS_ApplyUpdates(BSTR ProviderName/*[in]*/, VARIANT Delta/*[in]*/, 
                                        long MaxErrors/*[in]*/, long* ErrorCount/*[out]*/, 
                                        VARIANT* OwnerData/*[in,out]*/)
{
  VARIANT Value;
  this->AS_ApplyUpdates(ProviderName, Delta, MaxErrors, ErrorCount, OwnerData, (VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITest13bServerDispT<T>::AS_GetRecords(BSTR ProviderName/*[in]*/, long Count/*[in]*/, 
                                      long* RecsOut/*[out]*/, long Options/*[in]*/, 
                                      BSTR CommandText/*[in]*/, VARIANT* Params/*[in,out]*/, 
                                      VARIANT* OwnerData/*[in,out]*/, VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_GetRecords"), DISPID(20000001));
  TAutoArgs<7> _args;
  _args[1] = ProviderName /*[VT_BSTR:0]*/;
  _args[2] = Count /*[VT_I4:0]*/;
  _args[3] = RecsOut /*[VT_I4:1]*/;
  _args[4] = Options /*[VT_I4:0]*/;
  _args[5] = CommandText /*[VT_BSTR:0]*/;
  _args[6] = Params /*[VT_VARIANT:1]*/;
  _args[7] = OwnerData /*[VT_VARIANT:1]*/;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
ITest13bServerDispT<T>::AS_GetRecords(BSTR ProviderName/*[in]*/, long Count/*[in]*/, 
                                      long* RecsOut/*[out]*/, long Options/*[in]*/, 
                                      BSTR CommandText/*[in]*/, VARIANT* Params/*[in,out]*/, 
                                      VARIANT* OwnerData/*[in,out]*/)
{
  VARIANT Value;
  this->AS_GetRecords(ProviderName, Count, RecsOut, Options, CommandText, Params, OwnerData, (VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITest13bServerDispT<T>::AS_DataRequest(BSTR ProviderName/*[in]*/, VARIANT Data/*[in]*/, 
                                       VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_DataRequest"), DISPID(20000002));
  TAutoArgs<2> _args;
  _args[1] = ProviderName /*[VT_BSTR:0]*/;
  _args[2] = Data /*[VT_VARIANT:0]*/;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
ITest13bServerDispT<T>::AS_DataRequest(BSTR ProviderName/*[in]*/, VARIANT Data/*[in]*/)
{
  VARIANT Value;
  this->AS_DataRequest(ProviderName, Data, (VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITest13bServerDispT<T>::AS_GetProviderNames(VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_GetProviderNames"), DISPID(20000003));
  TAutoArgs<0> _args;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
ITest13bServerDispT<T>::AS_GetProviderNames(void)
{
  VARIANT Value;
  this->AS_GetProviderNames((VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITest13bServerDispT<T>::AS_GetParams(BSTR ProviderName/*[in]*/, VARIANT* OwnerData/*[in,out]*/, 
                                     VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_GetParams"), DISPID(20000004));
  TAutoArgs<2> _args;
  _args[1] = ProviderName /*[VT_BSTR:0]*/;
  _args[2] = OwnerData /*[VT_VARIANT:1]*/;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
ITest13bServerDispT<T>::AS_GetParams(BSTR ProviderName/*[in]*/, VARIANT* OwnerData/*[in,out]*/)
{
  VARIANT Value;
  this->AS_GetParams(ProviderName, OwnerData, (VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITest13bServerDispT<T>::AS_RowRequest(BSTR ProviderName/*[in]*/, VARIANT Row/*[in]*/, 
                                      long RequestType/*[in]*/, VARIANT* OwnerData/*[in,out]*/, 
                                      VARIANT* Value/*[out,retval]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_RowRequest"), DISPID(20000005));
  TAutoArgs<4> _args;
  _args[1] = ProviderName /*[VT_BSTR:0]*/;
  _args[2] = Row /*[VT_VARIANT:0]*/;
  _args[3] = RequestType /*[VT_I4:0]*/;
  _args[4] = OwnerData /*[VT_VARIANT:1]*/;
  return OutRetValSetterPtr(Value /*[VT_VARIANT:1]*/, _args, OleFunction(_dispid, _args));
}

template <class T> VARIANT __fastcall
ITest13bServerDispT<T>::AS_RowRequest(BSTR ProviderName/*[in]*/, VARIANT Row/*[in]*/, 
                                      long RequestType/*[in]*/, VARIANT* OwnerData/*[in,out]*/)
{
  VARIANT Value;
  this->AS_RowRequest(ProviderName, Row, RequestType, OwnerData, (VARIANT*)&Value);
  return Value;
}

template <class T> HRESULT __fastcall
ITest13bServerDispT<T>::AS_Execute(BSTR ProviderName/*[in]*/, BSTR CommandText/*[in]*/, 
                                   VARIANT* Params/*[in,out]*/, VARIANT* OwnerData/*[in,out]*/)
{
  _TDispID _dispid(*this, OLETEXT("AS_Execute"), DISPID(20000006));
  TAutoArgs<4> _args;
  _args[1] = ProviderName /*[VT_BSTR:0]*/;
  _args[2] = CommandText /*[VT_BSTR:0]*/;
  _args[3] = Params /*[VT_VARIANT:1]*/;
  _args[4] = OwnerData /*[VT_VARIANT:1]*/;
  return OleFunction(_dispid, _args);
}

// *********************************************************************//
// The following typedefs expose classes (named CoCoClassName) that       
// provide static Create() and CreateRemote(LPWSTR machineName) methods   
// for creating an instance of an exposed object. These functions can     
// be used by client wishing to automate CoClasses exposed by this        
// typelibrary.                                                           
// *********************************************************************//

// *********************************************************************//
// COCLASS DEFAULT INTERFACE CREATOR
// CoClass  : Test12aServer
// Interface: TCOMITest13bServer
// *********************************************************************//
typedef TCoClassCreatorT<TCOMITest13bServer, ITest13bServer, &CLSID_Test12aServer, &IID_ITest13bServer> CoTest12aServer;
#endif  //   __TLB_NO_INTERFACE_WRAPPERS


};     // namespace Project13b_tlb

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Project13b_tlb;
#endif

#pragma option pop

#endif // Project13b_TLBH
